### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by profiluefter** [RexSkz/json-diff-kit#12]
Hi,
there are already a few issues due to build problems however the error I'm getting is not among them.

After adding an import of the package to my next.js project (using TypeScript) I get the following error:

```
error - ...\node_modules\json-diff-kit\dist\index.js:2453
import * as React from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at json-diff-kit (...\.next\server\pages\audit.js:339:18)
    at __webpack_require__ (...\.next\server\webpack-runtime.js:33:42) {
  page: '/audit'
}
```

The mentioned (compiled) file does indeed contain the import:
![grafik](https://user-images.githubusercontent.com/18028031/210657635-c78e7056-2555-41d2-ba2d-bfbad46012d8.png)

This is the only import in this compiled file so I guess it is a build error and the other imports got adjusted properly.

Maybe this import could be adjusted to just import the used function/types/etc and not everything and that might resolve the issue: https://github.com/RexSkz/json-diff-kit/blob/2b60eddfab505b5b46dd4352401c411bae4b1c57/src/viewer.tsx#L1

Also just in case this import exists because it was necessary to import React in older versions of React, [this is no longer the case](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports).

**Comment by profiluefter** [comment]
Downgrading to version `1.0.8` fixed it for me eventhough the import is still present in the compiled dist file. Weird

**Comment by Inventsable** [comment]
It would also be nice to not need React considering I was planning to use this for Vue and the README even mentions Vue specifically.

**Comment by pgarr** [comment]
Wouldn't be enough to switch `import * as React from "react";`  to `import * as React from "react";` ?

**Comment by profiluefter** [comment]
I'm not sure but I would just switch it to only import the things which are actually needed. Might send a PR later if I remember to
