### ISSUE TITLE
Comparing a non object with a object produces a non beautified object.

### ISSUE THREAD

**Issue by zthun** [RexSkz/json-diff-kit#13]
The following happens on the demo if you have an intrinsic value that is compared with an object.

![image](https://user-images.githubusercontent.com/2132881/227326284-fcfa3b3a-77bd-44dc-ad9c-0b0ab32c3663.png)

Notice that the comparison of a: null to a: { object with values }, puts the resulting a all on one line instead of beautifying the JSON.  However, when c is undefined to now an object, it beautifies the JSON properly.  This also happens when the object on the right is contained in an array where it was not there before:

![image](https://user-images.githubusercontent.com/2132881/227327961-3aa6998d-0f02-4163-b6db-2d6c3b067e98.png)

Expected Behavior:  
- Output JSON differences are beautified and line broken similar to the comparison of undefined and object.

**Comment by RexSkz** [comment]
Hi, thanks for reporting this issue! I've added the "line wrapping" support for this situation, you can try it with `1.0.10` :)

Show modifications:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/27483702/227493964-15bba268-e59c-43d0-a06a-106debbaefbc.png">

Do not show modifications:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/27483702/227494042-e4a3ad7a-2b7b-47f6-8aff-aa32a4e8828d.png">
