### ISSUE TITLE
Possible configuration for changing the highlighter color in Viewer 

### ISSUE THREAD

**Issue by mdislam** [RexSkz/json-diff-kit#19]
Hi Is it possible to customise the highlighter color?

For example, If there is difference in values between 2 JSONs, then I would like to have "purple" highlighter instead of orange?

Regards,
mesbahul

**Comment by RexSkz** [comment]
Definitely yes! There's a prop `bgColour` in the `<Viewer>` component. You can use it like this:

```js
<Viewer
  bgColour={{
    // add: 'green',
    // remove: 'red',
    modify: 'purple',
  }}
/>
```

The result should be as expected:

<img width="892" alt="image" src="https://github.com/RexSkz/json-diff-kit/assets/27483702/f5eeec88-10a7-4b74-905a-d964152ed289">
