### ISSUE TITLE
Babel error

### ISSUE THREAD

**Issue by vinuganesan** [RexSkz/json-diff-kit#2]
Hi,

I'm getting a babel error "Support for the experimental syntax 'classProperties' isn't currently enabled". I added @babel/plugin-proposal-class-properties and configured my babel file(.babelrc) still not working. Can you help me to solve this issue.

![babel-error](https://user-images.githubusercontent.com/7202549/177044112-2b2b5eb4-6e25-4ec2-86d1-d5054f6ca4f2.png)

Thanks.

**Comment by RomikimoR** [comment]
Hello, My error is slightly different but means the same:

```
node_modules/json-diff-kit/dist/index.js: Missing class properties transform.
  715 | // src/differ.ts
  716 | var Differ = class {
> 717 |   options;
      |   ^
  718 |   arrayDiffFunc;
  719 |   constructor({
  720 |     detectCircular: detectCircular2 = true,
```

I also added the package with  npm install --save-dev @babel/plugin-proposal-class-properties and try to configure either my webpack config or even create a .babelrc file but nothing work.

Any idea ? 
Thanks

**Comment by RexSkz** [comment]
This may be due to the compiled result by ESBuild. I'll investigate it later.

**Comment by RexSkz** [comment]
I didn't find the error in my example app created by the `create-react-app`.

https://github.com/RexSkz/test-babel-class-properties

Could you please provide more details, such as the `.babelrc` file, or a minimal example?

**Comment by ipramono** [comment]
Found the same issue. 
`import { Differ, Viewer } from "json-diff-kit";
import "json-diff-kit/dist/viewer.css";
const differ = new Differ({
          detectCircular: true, // default `true`
          maxDepth: Infinity, // default `Infinity`
          showModifications: true, // default `true`
          arrayDiffMethod: "lcs", // default `"normal"`, but `"lcs"` may be more useful
        });
        const diff = differ.diff(changeRequest.before, changeRequest.after);

        return (
          <Viewer
            diff={diff} // required
            indent={4} // default `2`
            lineNumbers={false} // default `false`
            highlightInlineDiff={true} // default `false`
            inlineDiffOptions={{
              mode: "word", // default `"char"`, but `"word"` may be more useful
              wordSeparator: " ", // default `""`, but `" "` is more useful for sentences
            }}
          />
        );`

**Comment by RexSkz** [comment]
@ipramono Can you provide your babel version and the `babelrc` file?

**Comment by ipramono** [comment]
@RexSkz I don't have babelrc, and there's no babel in my package.json

**Comment by number-00** [comment]
I was also getting this error and it got resolved after I changed 

"react": "^16.14.0",
"react-dom": "^16.14.0",
 "react-scripts": "3.4.1",
to 

"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-scripts": "5.0.1",
"web-vitals": "^2.1.4",

in my package.json file
