### ISSUE TITLE
Comparing array with the same array with added object produces a non beautified object

### ISSUE THREAD

**Issue by k-rokicki** [RexSkz/json-diff-kit#24]
![Screenshot 2023-10-19 at 6 20 23 PM](https://github.com/RexSkz/json-diff-kit/assets/39855819/77204e8d-48f4-4c8c-9f98-a017803aee76)
I believe this behavior was supposed to be fixed in #13, so I would appreciate if you could tell me if I need to change some options or if this is actually a bug.

**Comment by RexSkz** [comment]
It's fixed in `1.0.19`, please have a try :)

![image](https://github.com/RexSkz/json-diff-kit/assets/27483702/fd6d143a-9c29-446d-84e5-1aca95efebc8)

**Comment by k-rokicki** [comment]
Fantastic, thank you very much!
