### ISSUE TITLE
Key order wasn't respected

### ISSUE THREAD

**Issue by Paper-Folding** [RexSkz/json-diff-kit#26]
### What happened?
The diff result does not respect original json object's key order.

### Reproduce
Just see this [example](https://json-diff-kit.js.org/#l=%7B%0A+%22z%22%3A+5%2C%0A+%22a%22%3A+123%0A%7D&r=%7B%0A+%22z%22%3A+15%2C%0A+%22a%22%3A+345%0A%7D), the key order is `["z", "a"]` in original object, but turns into `["a", "z"]` after perform diff operation.

**Comment by Paper-Folding** [comment]
`lineNumber` field also did not respect the key order.

**Comment by RexSkz** [comment]
The key order does not affect JSON value, the following two JSONs should be assumed equal:

```json
{ "a": 1, "z": 2 }
{ "z": 2, "a": 1 }
```

I think the behaviour of json-diff-kit is acceptable. Also, the algorithm relies on this behaviour - it scans keys on both sides from small to large (based on ASCII value).

---

If we should respect the key order (on which side?), we would not be able to display the "modified" lines (the yellow lines).

```text
{         | {
  "a": 1, |   "z": 2,
  "z": 2  |   "a": 1
}         | }
```

**Comment by Paper-Folding** [comment]
Thank you for your reply!
You are right, but I think at least a field (say "lineIndex" for example) should be provided to indicate all lines original position, users will not like to see their json object being re-ordered, for example, user wouldn't like to see   
```json
{
    "start_date": "20201231",
    "end_date": "20210101"
}
```
turns into  
```json
{
    "end_date": "20210101",
    "start_date": "20201231"
}
```

**Comment by RexSkz** [comment]
Your scenario seems reasonable; maybe we can add an option to let differ respect the key order:

```ts
interface DifferOptions {
  /**
   * If the value is set, differ will make sure the key order of results is the same as inputs ("before" or "after").
   * Otherwise, differ will sort the keys of results.
   */
  preserveKeyOrder?: 'before' | 'after';
}
```

**Comment by RexSkz** [comment]
Supported from `1.0.20`; playground is also updated.

**Comment by Paper-Folding** [comment]
Wrong result of this [example](https://json-diff-kit.js.org/#l=%7B%0A++%22a%22%3A+1%2C%0A++%22z%22%3A+1%0A%7D&r=%7B%0A++%22z%22%3A+1%2C%0A++%22b%22%3A+1%0A%7D) when using `preserveKeyOrder: "after"` .

**Comment by RexSkz** [comment]
It's because of a bug that I forgot to change the compare operator to the `cmp` result. It should be okay now.
