### ISSUE TITLE
'Show lines before' button is not working properly when there is no difference

### ISSUE THREAD

**Issue by AlgiBayer** [RexSkz/json-diff-kit#30]
<img width="1510" alt="image" src="https://github.com/RexSkz/json-diff-kit/assets/132572671/2329f0c0-faf9-4a4a-b9fb-a99266da6dac">
<img width="1496" alt="image" src="https://github.com/RexSkz/json-diff-kit/assets/132572671/31edcbcd-5d44-4771-bf0c-e3fe3c9a5532">

When I clicked to the show lines before it is unfortunately not showing the previous lines. Could you please look at this bug?
Thanks in advance.

**Comment by RexSkz** [comment]
It's an edge case of `hideUnchangedLines`.

If two JSONs are equal, maybe we should show the message `No change detected` at the beginning and then display all lines. If the `hideUnchangedLines` prop is set, we just display the message.

**Comment by RexSkz** [comment]
Fixed in 1.0.22, playground is also updated.
