### ISSUE TITLE
Module not found: Error: Can't resolve 'json-diff-kit'

### ISSUE THREAD

**Issue by gladsonrobinson** [RexSkz/json-diff-kit#4]

**Comment by dhurley-arine** [comment]
I can confirm that this is also happening to me, specifically when trying to run tests in Jest that make use of the file. No issues when importing or running normally.

**Comment by RexSkz** [comment]
Hello, can you provide a minimum repository to reproduce this issue?

Before seeing the code, I can only tell it may be due to the ESM stuff...

**Comment by alexturpin** [comment]
Using `tsx` causes the same issue. It's because the package.json uses `module` instead of `main`.
