### ISSUE TITLE
Same object detected as newly added

### ISSUE THREAD

**Issue by xhonato** [RexSkz/json-diff-kit#6]
Hello.

I found out the following issue while running some test cases.

As you can see I've the same object on the right side and added one object above and one below of it. The library detects that the text of the left object was changed.

<img width="1159" alt="Screenshot 2022-11-29 at 15 31 18" src="https://user-images.githubusercontent.com/14541825/204556733-11071734-5efc-4ce2-be82-641c8fba1ff0.png">

**Comment by RexSkz** [comment]
Hello, I just released `v1.0.9-alpha.3`, which provides a differ option `recursiveEqual` (default `false`) that uses `lodash.isEqual` when diffing arrays. Please have a try :)

The document has also been updated.

![image](https://user-images.githubusercontent.com/27483702/209420473-448be094-8d78-4e5c-a6a7-6c9c704abb09.png)

![image](https://user-images.githubusercontent.com/27483702/209420479-310816c9-2376-4248-b189-9e51a4a46372.png)
